openapi: 3.0.0
info:
  title: amlight/sdntrace_cp
  version: '0.1'
  description: An OpenFlow Path Tracing on Control Plane
paths:
  /api/amlight/sdntrace_cp/trace:
    put:
      summary: Trace a path
      description: Trace a path starting with the switch given with the parameters given. The trace is done entirely in control plane.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                trace:
                  type: object
                  required:
                    - switch
                  properties:
                    switch:
                      type: object
                      required:
                        - dpid
                        - in_port
                      properties:
                        dpid:
                          type: string
                          description: Initial switch datapath ID
                          example: 00:00:00:00:00:00:00:01
                        in_port:
                          type: integer
                          description: Starting incoming port
                          example: 1
                    eth:
                      type: object
                      properties:
                        dl_vlan:
                          type: integer
                          description: VLAN ID. This is an integer in range [1, 4095] as in a network packet.
                          example: 100
                          minimum: 1
                          maximum: 4095
                        dl_type:
                          type: integer
                          description: Ethernet type
                          example: '0x8100'
                        dl_src:
                          type: string
                          description: Source MAC address
                          example: '01:23:45:67:89:ab'
                        dl_dst:
                          type: string
                          description: Destination MAC address
                          example: '23:45:67:89:ab:cd'
                    ip:
                      type: object
                      properties:
                        nw_src:
                          type: string
                          description: Source IP
                          example: 192.168.20.21
                        nw_dst:
                          type: string
                          description: Destination IP
                          example: 192.168.25.123
                        nw_proto:
                          type: integer
                          description: IP protocol
                          example: 6
                        nw_tos:
                          type: integer
                          description: IP TOS
                          example: 0
                    tp:
                      type: object
                      properties:
                        tp_src:
                          type: integer
                          description: Source transport port
                          example: 8761
                        tp_dst:
                          type: integer
                          description: Destination transport port
                          example: 80
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array 
                    items:
                      type: object
                      required:
                        - dpid
                        - port
                        - time
                        - type
                      properties:
                        dpid:
                          type: string
                          description: Switch datapath ID 
                          example: 00:00:00:00:00:00:00:01
                        port:
                          type: integer
                          description: Incoming port in the switch
                          example: 1
                        time:
                          type: string
                          description: Date time when the iteration was computed
                          example: "2022-01-25 13:44:52.387021"
                        type:
                          type: string
                          enum: ["starting", "intermediary", "last", "loop", "incomplete"]
                          description: Type of the step. May be "starting", "intermediary", "last", and "loop" or "incomplete" for failure.
                          example: "intermediary"
                        vlan:
                          type: integer
                          description: VLAN ID
                          example: 100
        400:
          description: "Parameter 'dpid' and/or 'in_port' is missing"
          content:
            application/json:
              schema:
                type: string
                example: Bad request
  /api/amlight/sdntrace_cp/traces:
    put:
      summary: Trace paths given switches
      description: Trace a path starting with each switch given in a list as parameter.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  trace:
                    type: object
                    required:
                      - switch
                    properties:
                      switch:
                        type: object
                        required:
                          - dpid
                          - in_port
                        properties:
                          dpid:
                            type: string
                            description: Initial switch datapath ID
                            example: 00:00:00:00:00:00:00:01
                          in_port:
                            type: integer
                            description: Starting incoming port
                            example: 1
                      eth:
                        type: object
                        properties:
                          dl_vlan:
                            type: integer
                            description: VLAN ID. This is an integer in range [1, 4095] as in a network packet.
                            example: 100
                            minimum: 1
                            maximum: 4095
                          dl_type:
                            type: integer
                            description: Ethernet type
                          dl_src:
                            type: string
                            description: Source MAC address
                          dl_dst:
                            type: string
                            description: Destination MAC address
                      ip:
                        type: object
                        properties:
                          nw_src:
                            type: string
                            description: Source IP
                            example: 192.168.20.21
                          nw_dst:
                            type: string
                            description: Destination IP
                            example: 192.168.25.123
                          nw_proto:
                            type: integer
                            description: IP protocol
                            example: 6
                          nw_tos:
                            type: integer
                            description: IP TOS
                            example: 0
                      tp:
                        type: object
                        properties:
                          tp_src:
                            type: integer
                            description: Source transport port
                            example: 8761
                          tp_dst:
                            type: integer
                            description: Destination transport port
                            example: 80
      responses:
        200:
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array 
                    items:
                      type: array
                      items:
                        type: object
                        required:
                          - dpid
                          - port
                          - time
                          - type
                        properties:
                          dpid:
                            type: string
                            description: Switch datapath ID 
                            example: 00:00:00:00:00:00:00:01
                          port:
                            type: integer
                            description: Incoming port in the switch
                            example: 1
                          time:
                            type: string
                            description: Date time when the iteration was computed
                            example: "2022-01-25 13:44:52.387021"
                          type:
                            type: string
                            enum: ["starting", "intermediary", "last", "loop", "incomplete"]
                            description: Type of the step. May be "starting", "intermediary", "last", and "loop" or "incomplete" for failure.
                            example: "intermediary"
                          vlan:
                            type: integer
                            description: VLAN ID
                            example: 100

